name: Check PR valid
on: 
  pull_request

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install
        run: npm install
      - name: Check
        run: npm run check && npm run fail-on-uncommitted
        