name: Check PR valid
on: 
  pull_request

jobs:
  check-pr-valid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install
        run: npm install
      - name: Check
        run: npm run check
      - name: Check for uncommitted changes
        id: check-changes
        uses: mskri/check-uncommitted-changes-action@v1.0.1
      - name: Fail on uncommitted changes
        if: steps.check-changes.outputs.changes != ''
        run: exit 1
        