name: Sync Typedocs to Wiki
on: 
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  sync_docs:
    name: Sync Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki-sync branch
        uses: actions/checkout@v2
        with:
          ref: 'wiki-sync'
      - uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: wiki-sync
      - name: Build typedocs
        run: | 
          npm install
          npm run doc:wiki
      - name: Commit typedocs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Updating typedocs'
          file_pattern: 'typedocs/**'
      - name: Sync typedocs with Wiki
        uses: kai-tub/external-repo-sync-action@v1
        with:
          source-directory: './typedocs'
          branch: 'wiki-sync'
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
