name: Sync Typedocs to Wiki
on:
  - push
  
permissions:
  contents: write
  
jobs:
  sync_docs:
    name: Sync Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
      - name: Build typedocs
        run: | 
          npm install
          npm run doc:wiki
      - name: Commit typedocs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Updating typedocs'
          file_pattern: 'typedocs/**'
      - name: Sync typedocs with Wiki
        uses: kai-tub/external-repo-sync-action@v1
        with:
          source-directory: './typedocs'
          branch: 'main'
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
