name: Update Typedocs
on: 
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  update-typedocs:
    name: Sync Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki-sync branch
        uses: actions/checkout@v2
        with:
          ref: 'wiki-sync'
      - uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: wiki-sync
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build typedocs
        run: | 
          npm install
          npm run doc:wiki
      - name: Commit typedocs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Updating typedocs'
          file_pattern: 'typedocs/**'
